### ISSUE TITLE
Quiero participar

### ISSUE THREAD

**Issue by Matheo-Soria** [AriInWonderland/ClasificacionEquipoISA#1]

**Comment by AriInWonderland** [comment]
Bro, que onda. Aprecio las ganas y la velocidad, fijate que en la repo hay un archivo con la primera etapa y la consigna. 
Srry si el README no se entiende tan bien, la verdad que mi github es medio pelo jaja.

Para participar hace un fork y ni bien termines y quieras la evaluacion presencial podes tirar un pull request o buscarnos a nosotros. 

GLHF!!!

**Comment by Ag3nte47nck** [comment]
[file:///C:/Users/mathe/Downloads/ISA.c](url)

**Comment by Matheo-Soria** [comment]
Hola recien llegue a casa y ya lo hice

**Comment by Matheo-Soria** [comment]
![image](https://user-images.githubusercontent.com/114421832/192381453-4b37b8ca-b0af-4293-b0bb-0af0c9ea1e66.png)

**Comment by AriInWonderland** [comment]
Holisss. 
Bien ahi por la velocidad, pero pls fijste bien el workflow de la prueba jaja.
Tenes que hacer un fork del repositorio y ahi subis el codigo, despues simplemente hacer una pull request y ya vamos a tenerlo para cuando sea el dia llamarte y hacer la evaluacion y eso. 
Ah y por favor agrega tu nomnre y curso a modo de comentario o en algun lado que se vea, mala mia por no aclarar. O bueno, acercate a nosotros y decinos: "Che soy tal" y fue jaja.

**Comment by Matheo-Soria** [comment]
matheo soria 4to b, igual lo hice en pseint y lo exporte a c

**Comment by AriInWonderland** [comment]
Listo, ya correji el archivo con el ejercicio, perdon por la falta de claridad.
[Adjunto documentacion orientada a la creacion de un Fork.](https://docs.github.com/en/get-started/quickstart/fork-a-repo)

**Comment by Ag3nte47nck** [comment]
lo subo ahi?

**Comment by Matheo-Soria** [comment]
ahi me llego dale, cuando me llamarias?

**Comment by AriInWonderland** [comment]
Ni bien se aclare la situacion actual vamos a empezar a llamar, asi que no antes del miercoles/jueves. Con suerte el jueves o el viernes podriamos coordinar.

**Comment by Matheo-Soria** [comment]
daleee, igual hay alguna cosas que no tengo tan claras me dedico mas a la programacion de videojuegos

**Comment by AriInWonderland** [comment]
Bro, checkea tu fork, falta el source code.

**Comment by Matheo-Soria** [comment]
fijate ahi si te deja

**Comment by AriInWonderland** [comment]
Listo! Te parece bien si ya cierro el issue?

**Comment by Matheo-Soria** [comment]
si
